### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by amenzhinsky** [cznic/sqlite#11]
Code:
```go
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/cznic/sqlite"
)

func main() {
	c, err := sql.Open("sqlite", "/tmp/test.sqlite3")
	if err != nil {
		panic(err)
	}
	defer c.Close()

	_, err = c.Exec("CREATE TABLE t1 (t INT)")
	if err != nil {
		panic(err)
	}

	for i := 0;; i++ {
		_, err := c.Exec("INSERT INTO t1 (t) VALUES (?)", i)
		if err != nil {
			panic(err)
		}
		fmt.Println(i)
	}
}
```

Output:
```
...
6563
6564
6565
6566 # always fails here
panic: database disk image is malformed (11)
```

**Comment by cznic** [comment]
Bug in any of the cc, ccir or virtual packages :disappointed:

**Comment by amenzhinsky** [comment]
If I'm inserting strings instead of ints I get this (seem like a golang error): 
```
unexpected fault address 0x0                                                                                                                                  
fatal error: fault                                                                                                                                            
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4f7e00]                                                                                       
                                                                                                                                                              
goroutine 1 [running]:                                                                                                                                        
runtime.throw(0x58120f, 0x5)                                                                                                                                  
        /usr/lib/go/src/runtime/panic.go:596 +0x95 fp=0xc4203e8960 sp=0xc4203e8940                                                                            
runtime.sigpanic()                                                                                                                                            
        /usr/lib/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc4203e89b0 sp=0xc4203e8960                                                                     
github.com/cznic/virtual.(*cpu).run(0xc4200800e0, 0x143bb, 0x0, 0x0, 0x0)                                                                                     
        /home/amenzhinsky/Development/go/src/github.com/cznic/virtual/cpu.go:1447 +0x41a0 fp=0xc4203e97b8 sp=0xc4203e89b0                                     
github.com/cznic/virtual.(*Thread).FFI(0xc4200800e0, 0x143bb, 0xc4203e98f0, 0x1, 0x1, 0xc4203e9970, 0x1, 0x1, 0x549ae0, 0xc420236e98, ...)                    
        /home/amenzhinsky/Development/go/src/github.com/cznic/virtual/thread.go:158 +0x217 fp=0xc4203e9898 sp=0xc4203e97b8                                    
github.com/cznic/virtual.(*Thread).FFI1(0xc4200800e0, 0x143bb, 0x6c56e0, 0xc420236e90, 0xc4203e9970, 0x1, 0x1, 0x540460, 0xc420236d00, 0x0)                   
        /home/amenzhinsky/Development/go/src/github.com/cznic/virtual/thread.go:110 +0xab fp=0xc4203e9910 sp=0xc4203e9898                                     
github.com/cznic/sqlite.(*stmt).step(0xc4202358c0, 0x7fa91ee022d0, 0x1, 0xc420228990, 0x1)                                                                    
        /home/amenzhinsky/Development/go/src/github.com/cznic/sqlite/sqlite.go:970 +0xe4 fp=0xc4203e9990 sp=0xc4203e9910                                      
github.com/cznic/sqlite.(*stmt).exec(0xc4202358c0, 0x7fa91f2f9c80, 0xc42000e2e0, 0xc420228990, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)                                  
        /home/amenzhinsky/Development/go/src/github.com/cznic/sqlite/sqlite.go:651 +0x216 fp=0xc4203e9a00 sp=0xc4203e9990                                     
github.com/cznic/sqlite.(*conn).exec(0xc42008e460, 0x7fa91f2f9c80, 0xc42000e2e0, 0x58643f, 0x1d, 0xc420228990, 0x1, 0x1, 0x0, 0x0, ...)                       
        /home/amenzhinsky/Development/go/src/github.com/cznic/sqlite/sqlite.go:1209 +0x180 fp=0xc4203e9a70 sp=0xc4203e9a00
```

**Comment by cznic** [comment]
> (seem like a golang error)

The panic line cpu.go:1447 seems like the VM has entered a corrupted state. My guess is that it's not in Go, but only debugging will tell. This will be non-trivial to figure out. FYI: It's possible to insert debug C printf's in the sqlite3.c code and then enable the debugWriter using -tags sqlite.trace. (go generate must be invoked after changing the sqlite3.c source, of course.)

**Comment by amenzhinsky** [comment]
I'll give it a try this weekend 😄

**Comment by cznic** [comment]
Will be appreciated :+1:

**Comment by cznic** [comment]
Also, I suggest to uncomment these [two lines]( https://github.com/cznic/sqlite/blob/a884a7b74b8900b0b2871b9e658292c145e38c05/generator.go#L287-L288).

**Comment by amenzhinsky** [comment]
That didn't help, I added added this code 
```go
fmt.Printf("--> %#v\n", c.sp)
fmt.Printf("==> %#v\n", readPtr(c.sp))
```
right before https://github.com/cznic/virtual/blob/master/cpu.go#L1447 where it panics

```
...
--> 0x7f6e76b94268                                                                                                                                            
==> 0x7f6e78a3c8a0                                                                                                                                            
--> 0x7f6e76b941f8                                                                                                                                            
==> 0x7f6e76b94228                                                                                                                                            
--> 0x7f6e76b941f8                                                                                                                                            
==> 0x7f6e76b94228                                                                                                                                            
--> 0x7f6e76b941f8                                                                                                                                            
==> 0x7f6e76b94208                                                                                                                                            
--> 0x7f6e76b941a8                                                                                                                                            
==> 0x7f6e76b941b0                                                                                                                                            
--> 0x7f6e76b941a8                                                                                                                                            
==> 0x7f6e78a3cbd0                                                                                                                                            
--> 0x7f6e76b941a8                                                                                                                                            
==> 0x7f6e78a3cbc8                                                                                                                                            
--> 0x7f6e76b941a8                                                                                                                                            
==> 0x6007f6e789f74e8  
```

And last address doesn't seem a valid memory address. Do you have any ideas?

btw: I'm on linux_amd64

**Comment by cznic** [comment]
:+1: That's actually a *very* valuable piece of information as it looks very much like a misaligned-by-four access corrupting an otherwise valid-looking pointer. It must be some stupid mistake/typo of mine, I think.

**Comment by cznic** [comment]
Another hint: It might be also worth trying to add -tags virtual.trace to the build, but the amount of generated output is prohibitive in non-trivial cases.

**Comment by amenzhinsky** [comment]
Adding the `virtual.trace` didn't help. It outputs too much information which is not very helpful because it looks like a backtrace.

**Comment by cznic** [comment]
@amenzhinsky Thanks again for the report, finally got time to look into it. FTR, if you wrap the writing loop in a transaction it runs orders of magnitude faster. Like [here](https://github.com/cznic/sqlite/blob/1a3b0a731a9d2b66fb058caef95c004634b17307/all_test.go#L478-L493).

**Comment by amenzhinsky** [comment]
@cznic. thanks, good job!
